# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-ios-fellipe-bravo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios-fellipe-bravo

  target 'desafio-ios-fellipe-bravoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-ios-fellipe-bravoUITests' do
    # Pods for testing
  end

end
