# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-ios-fellipe-bravo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios-fellipe-bravo
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxAlamofire'
  pod 'Kingfisher', '~> 5.14'

  target 'desafio-ios-fellipe-bravoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'desafio-ios-fellipe-bravoUITests' do
    # Pods for testing
  end

end
